### ISSUE TITLE
Newest .NET core doesn't support project.json projects anymore.

### ISSUE THREAD

**Issue by Janobob** [swisscom/cf-default-app-dotnetcore#1]
Upgrading to the newest .NET Core **breaks** the build (dotnet restore and dotnet build).

I recommend migrating to the new format of .csproj files.

```
dotnet restore
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

**Comment by wapacro** [comment]
Fixed with https://github.com/swisscom/cf-default-app-dotnetcore/commit/258af8a78640341a0dc48c45b8a0df7a9a36edce
